version: "3.9"
services:

  postgres:
    image: postgres
    container_name: dtb_postgres
    environment:
      POSTGRES_DB: "yes_project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: dtb_django
    command:  bash -c "python django_controller/manage.py migrate && python django_controller/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  bot:
    build: .
    container_name: dtb_bot
    command: python app.py
    env_file:
      - ./.env
    depends_on:
      - web
