# Generated by Django 3.2.9 on 2021-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('text', models.CharField(max_length=200, verbose_name='Описание товара')),
                ('category_name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('category_code', models.CharField(max_length=20, verbose_name='Код категории')),
                ('subcategory_name', models.CharField(max_length=50, verbose_name='Название подкатегории')),
                ('subcategory_code', models.CharField(max_length=50, verbose_name='Код подкатегории')),
                ('promocode_index', models.CharField(max_length=20, verbose_name='Ключ промокода')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Уникальный ID telegram')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('yes_coin_balance', models.IntegerField(default=0, verbose_name='Баланс YesCoin')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'users',
            },
        ),
    ]
