# Generated by Django 3.2.9 on 2021-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен')], max_length=50, verbose_name='Статус заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('sum', models.IntegerField(verbose_name='Сумма заказа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('login', models.CharField(max_length=100, verbose_name='Логин в телеграме')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Уникальный ID telegram')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен')], max_length=50, verbose_name='Статус заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('sum', models.IntegerField(verbose_name='Сумма заказа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('login', models.CharField(max_length=100, verbose_name='Логин в телеграме')),
                ('user_id', models.BigIntegerField(verbose_name='Уникальный ID telegram')),
            ],
            options={
                'verbose_name': 'Покупка Выполненная',
                'verbose_name_plural': 'Покупки Выполненные',
                'db_table': 'purchase_confirmed',
            },
        ),
    ]
