# Generated by Django 3.2.9 on 2021-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Уникальный ID telegram'),
        ),
    ]
