# Generated by Django 3.2.9 on 2021-12-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_promocodes_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodes_orders',
            options={'verbose_name': 'Покупка промокод', 'verbose_name_plural': 'Покупки промокодов'},
        ),
        migrations.AlterModelTable(
            name='promocodes_orders',
            table='promocodes_orders',
        ),
    ]
