# Generated by Django 3.2.9 on 2021-12-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20211225_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes_orders',
            name='data',
            field=models.CharField(max_length=200, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promocodes_orders',
            name='index',
            field=models.CharField(max_length=100, null=True, verbose_name='Ключ промокода'),
        ),
    ]
