# Generated by Django 3.2.9 on 2021-12-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20211228_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocodes_orders',
        ),
    ]
